-- Run this script in the Supabase SQL editor.
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  interest text not null,
  message text not null
);

alter table public.inquiries enable row level security;

create policy "Anyone can submit an inquiry"
on public.inquiries for insert
to anon, authenticated
with check (true);

-- Keep reading private: submissions are only inserted by the public form.
